# This file has been autogenerated by the pywayland scanner

# VENDORED FILE -- do not edit by hand.
#
# Generated by pywayland 0.4.19 scanner from the protocol XMLs vendored in
# this repo at launcher/data/. Upstream pywayland ships no
# wlr_foreign_toplevel_management_unstable_v1 module, so the generated output
# is committed here to make the switcher backend work out of the box.
#
# Regenerate with (from the repo root, .venv active):
#
#   sed 's/ interface="wl_object"//g' launcher/data/wayland.xml > /tmp/wayland.xml
#   python -m pywayland.scanner -o launcher/src/wayland_proto \
#       -i /tmp/wayland.xml launcher/data/wlr-foreign-toplevel-management-unstable-v1.xml
#
# The sed step drops the stale `interface="wl_object"` attribute carried by
# the vendored (older-revision) wayland.xml; pywayland's scanner requires
# every referenced interface to be declared in one of its input files, and
# wl_object is not a declared interface. Upstream's own generated module
# types that argument as plain `object` too.

# Copyright © 2008-2011 Kristian Høgsberg
# Copyright © 2010-2011 Intel Corporation
# Copyright © 2012-2013 Collabora, Ltd.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice (including the
# next paragraph) shall be included in all copies or substantial
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from __future__ import annotations

import enum

from typing import Any

from pywayland.protocol_core import Argument, ArgumentType, Global, Interface, Proxy, Resource


class WlBuffer(Interface):
    """Content buffer

    A buffer provides the content for a
    :class:`~pywayland.protocol.wayland.WlSurface`. Buffers are created by
    factory functions such as :func:`WlShmPool.create_buffer()
    <pywayland.protocol.wayland.WlShmPool.create_buffer>`.
    """

    name = "wl_buffer"
    version = 1


class WlCallback(Interface):
    """Callback object

    Clients can handle the 'done' event to get notified when the related
    request is done.
    """

    name = "wl_callback"
    version = 1


class WlCompositor(Interface):
    """The compositor singleton

    A compositor.  This object is a singleton global.  The compositor is
    responsible for combining the contents of multiple surfaces into one final
    image presented to the user.
    """

    name = "wl_compositor"
    version = 4


class WlDataDevice(Interface):
    """Data transfer device

    There is one :class:`WlDataDevice` per seat that can be used to transfer
    data between clients.
    """

    name = "wl_data_device"
    version = 3


class WlDataDeviceManager(Interface):
    """Data transfer interface

    The :class:`WlDataDeviceManager` is a singleton global object that provides
    access to the inter-client data transfer mechanisms such as copy-and-paste
    and drag-and-drop.
    """

    name = "wl_data_device_manager"
    version = 3


class WlDataOffer(Interface):
    """Offer to transfer data

    A :class:`WlDataOffer` represents a piece of data offered for transfer by
    another client (the source client).  It is used by the data-device
    mechanism.
    """

    name = "wl_data_offer"
    version = 3


class WlDataSource(Interface):
    """Offer to transfer data

    The :class:`WlDataSource` object is the source side of a
    :class:`~pywayland.protocol.wayland.WlDataOffer`. It is created by the
    source client and used by the compositor to present the data to the user.
    """

    name = "wl_data_source"
    version = 3


class WlDisplay(Interface):
    """Core global object

    The core global object.  This is a special singleton object.  It is used
    for internal Wayland protocol features.
    """

    name = "wl_display"
    version = 1


class WlKeyboard(Interface):
    """Keyboard input device

    The :class:`WlKeyboard` interface represents one or more keyboards
    associated with a seat.
    """

    name = "wl_keyboard"
    version = 7

    class keymap_format(enum.IntEnum):
        no_keymap = 0
        xkb_v1 = 1

    class key_state(enum.IntEnum):
        released = 0
        pressed = 1


class WlOutput(Interface):
    """Compositor output region

    An output describes part of the compositor geometry.  The compositor works
    in the 'compositor coordinate system'.
    """

    name = "wl_output"
    version = 4

    class subpixel(enum.IntEnum):
        unknown = 0
        none = 1
        horizontal_rgb = 2
        horizontal_bgr = 3
        vertical_rgb = 4
        vertical_bgr = 5

    class transform(enum.IntEnum):
        normal = 0
        transform_90 = 1
        transform_180 = 2
        transform_270 = 3
        flipped = 4
        flipped_90 = 5
        flipped_180 = 6
        flipped_270 = 7

    class mode(enum.IntEnum):
        current = 0x1
        preferred = 0x2


class WlPointer(Interface):
    """Pointer input device

    The :class:`WlPointer` interface represents one or more input devices, such
    as mice, which belong to the seat.
    """

    name = "wl_pointer"
    version = 7

    class error(enum.IntEnum):
        role = 0

    class button_state(enum.IntEnum):
        released = 0
        pressed = 1

    class axis(enum.IntEnum):
        vertical_scroll = 0
        horizontal_scroll = 1

    class axis_source(enum.IntEnum):
        wheel = 0
        finger = 1
        continuous = 2


class WlRegion(Interface):
    """Region interface

    A region object describes an area.
    """

    name = "wl_region"
    version = 1


class WlRegistry(Interface):
    """Global registry object

    The singleton global registry object.  The server has a number of global
    objects that are available to all clients.  These objects typically
    represent an actual object in the server (for example, an input device) or
    are singleton objects that provide extension functionality.

    When a client creates a registry object, the registry object will emit a
    global event for each global in the registry.  Globals are removed by
    sending a global_remove event to send "bind" requests to the compositor.
    The client must not bind more than once to the same global.
    """

    name = "wl_registry"
    version = 1


class WlSeat(Interface):
    """Group of input devices

    A seat is a group of keyboards, pointer and touch devices. This object is
    published as a global during start up, or when such a device is hot
    plugged.
    """

    name = "wl_seat"
    version = 7

    class capability(enum.IntEnum):
        pointer = 1
        keyboard = 2
        touch = 4


class WlShell(Interface):
    """Create desktop-style surfaces

    This interface is implemented by the server and provides desktop-style user
    interfaces.
    """

    name = "wl_shell"
    version = 1


class WlShellSurface(Interface):
    """Desktop-style metadata interface

    An interface that may be implemented by a
    :class:`~pywayland.protocol.wayland.WlSurface`, for implementations that
    provide a desktop-style user interface.
    """

    name = "wl_shell_surface"
    version = 1

    class resize(enum.IntEnum):
        none = 0
        top = 1
        bottom = 2
        left = 4
        top_left = 5
        bottom_left = 6
        right = 8
        top_right = 9
        bottom_right = 10

    class transient(enum.IntEnum):
        inactive = 0x1

    class fullscreen_method(enum.IntEnum):
        default = 0
        scale = 1
        driver = 2
        copy = 3


class WlShm(Interface):
    """Shared memory support

    A singleton global object that provides support for shared memory.
    """

    name = "wl_shm"
    version = 1

    class error(enum.IntEnum):
        invalid_format = 0
        invalid_stride = 1
        invalid_fd = 2

    class format(enum.IntEnum):
        argb8888 = 0
        xrgb8888 = 1
        c8 = 0x20203843
        rgb332 = 0x38424752
        bgr233 = 0x38524742
        xrgb4444 = 0x32315258
        xbgr4444 = 0x32314258
        rgb565 = 0x36314752
        bgr565 = 0x36314742
        rgb888 = 0x34324752
        bgr888 = 0x34324742
        xbgr8888 = 0x34324258
        rgbx8888 = 0x38385252
        bgrx8888 = 0x38385242
        yuyv = 0x56595559
        yvyu = 0x55595659
        uyvy = 0x59565955
        vyuy = 0x59555956
        nv12 = 0x3231564E
        nv21 = 0x3132564E
        nv16 = 0x3631564E
        nv61 = 0x3136564E
        yuv410 = 0x39565559
        yvu410 = 0x39555659
        yuv411 = 0x31315559
        yvu411 = 0x31315659
        yuv420 = 0x32315559
        yvu420 = 0x32315659
        yuv444 = 0x34325559
        yvu444 = 0x34325659
        r8 = 0x20203852
        r16 = 0x20363152
        rg88 = 0x38384752
        gr88 = 0x38384747
        rg1616 = 0x36314752
        gr1616 = 0x36314747
        xrgb16161616f = 0x48345258
        xbgr16161616f = 0x48344258
        abgr16161616f = 0x48344241
        argb16161616f = 0x48345241


class WlShmPool(Interface):
    """A shared memory pool

    The :class:`WlShmPool` object encapsulates a piece of memory shared between
    the compositor and the client.  On the server side, the object is
    automatically destroyed when the :func:`WlShmPool.destroy()` request is
    received.  :class:`WlShmPool` objects are created by the
    :func:`WlShm.create_pool() <pywayland.protocol.wayland.WlShm.create_pool>`
    request.
    """

    name = "wl_shm_pool"
    version = 1


class WlSubcompositor(Interface):
    """Sub-surface compositing

    The global interface exposing sub-surface compositing capabilities.
    """

    name = "wl_subcompositor"
    version = 1


class WlSubsurface(Interface):
    """Sub-surface interface to a :class:`~pywayland.protocol.wayland.WlSurface`

    An additional interface to a :class:`~pywayland.protocol.wayland.WlSurface`
    object, which has been made a sub-surface.
    """

    name = "wl_subsurface"
    version = 1


class WlSurface(Interface):
    """An onscreen surface

    A surface is a rectangular area that is displayed on the screen. It has a
    location, size and pixel contents.
    """

    name = "wl_surface"
    version = 4


class WlTouch(Interface):
    """Touchscreen input device

    The :class:`WlTouch` interface represents a touchscreen associated with a
    seat.
    """

    name = "wl_touch"
    version = 7


class WlBufferResource(Resource[WlBuffer]):
    interface = WlBuffer

    @WlBuffer.event()
    def release(self) -> None:
        """Compositor releases buffer

        Sent when this :class:`WlBuffer` is no longer used by the compositor.
        The client is now free to reuse or destroy this buffer and its backing
        storage.
        """
        self._post_event(0)


class WlCallbackResource(Resource[WlCallback]):
    interface = WlCallback

    @WlCallback.event(
        Argument(ArgumentType.Uint),
    )
    def done(self, callback_data: int) -> None:
        """Done event

        Notify the client when the related request is done.

        :param callback_data:
            request-specific data for the callback
        :type callback_data:
            `ArgumentType.Uint`
        """
        self._post_event(0, callback_data)


class WlCompositorResource(Resource[WlCompositor]):
    interface = WlCompositor


class WlDataDeviceResource(Resource[WlDataDevice]):
    interface = WlDataDevice

    @WlDataDevice.event(
        Argument(ArgumentType.NewId, interface=WlDataOffer),
    )
    def data_offer(self, id: WlDataOffer) -> None:
        """Introduce a new :class:`~pywayland.protocol.wayland.WlDataOffer`

        The data_offer event introduces a new
        :class:`~pywayland.protocol.wayland.WlDataOffer` object, which will
        subsequently be used in either the data_device.enter event (for drag-
        and-drop) or the data_device.selection event (for selections).

        :param id:
            the new data_offer object
        :type id:
            :class:`~pywayland.protocol.wayland.WlDataOffer`
        """
        self._post_event(0, id)

    @WlDataDevice.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlSurface),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Object, interface=WlDataOffer, nullable=True),
    )
    def enter(self, serial: int, surface: WlSurface, x: float, y: float, id: WlDataOffer | None) -> None:
        """Initiate drag-and-drop session

        This event is sent when an active drag-and-drop pointer enters the
        surface owned by the client.

        :param serial:
            serial number of the pointer enter
        :type serial:
            `ArgumentType.Uint`
        :param surface:
            client surface entered
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :param x:
            surface-local x coordinate
        :type x:
            `ArgumentType.Fixed`
        :param y:
            surface-local y coordinate
        :type y:
            `ArgumentType.Fixed`
        :param id:
            source data_offer object
        :type id:
            :class:`~pywayland.protocol.wayland.WlDataOffer` or `None`
        """
        self._post_event(1, serial, surface, x, y, id)

    @WlDataDevice.event()
    def leave(self) -> None:
        """End drag-and-drop session

        This event is sent when the drag-and-drop pointer leaves the surface
        and the session ends.
        """
        self._post_event(2)

    @WlDataDevice.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Fixed),
    )
    def motion(self, time: int, x: float, y: float) -> None:
        """Drag-and-drop session motion

        This event is sent when the drag-and-drop pointer moves.

        :param time:
            timestamp with millisecond granularity
        :type time:
            `ArgumentType.Uint`
        :param x:
            surface-local x coordinate
        :type x:
            `ArgumentType.Fixed`
        :param y:
            surface-local y coordinate
        :type y:
            `ArgumentType.Fixed`
        """
        self._post_event(3, time, x, y)

    @WlDataDevice.event()
    def drop(self) -> None:
        """End drag-and-drop session successfully

        The event is sent when a drag-and-drop operation is ended because the
        implicit grab is released.
        """
        self._post_event(4)

    @WlDataDevice.event(
        Argument(ArgumentType.Object, interface=WlDataOffer, nullable=True),
    )
    def selection(self, id: WlDataOffer | None) -> None:
        """Advertise a selection

        The selection event is sent out to notify the client of a new
        :class:`~pywayland.protocol.wayland.WlDataOffer` for the selection for
        this device.

        :param id:
            selection data_offer object
        :type id:
            :class:`~pywayland.protocol.wayland.WlDataOffer` or `None`
        """
        self._post_event(5, id)


class WlDataDeviceManagerResource(Resource[WlDataDeviceManager]):
    interface = WlDataDeviceManager


class WlDataOfferResource(Resource[WlDataOffer]):
    interface = WlDataOffer

    @WlDataOffer.event(
        Argument(ArgumentType.String),
    )
    def offer(self, mime_type: str) -> None:
        """Advertise offered mime type

        Sent immediately after creating the :class:`WlDataOffer` object.  One
        event per offered mime type.

        :param mime_type:
            offered mime type
        :type mime_type:
            `ArgumentType.String`
        """
        self._post_event(0, mime_type)

    @WlDataOffer.event(
        Argument(ArgumentType.Uint),
        version=3,
    )
    def source_actions(self, source_actions: int) -> None:
        """Notify the source-side available actions

        This event indicates the actions offered by the data source.

        :param source_actions:
            actions offered by the data source
        :type source_actions:
            `ArgumentType.Uint`
        """
        self._post_event(1, source_actions)

    @WlDataOffer.event(
        Argument(ArgumentType.Uint),
        version=3,
    )
    def action(self, dnd_action: int) -> None:
        """Notify the selected action

        This event indicates the action selected by the compositor after
        matching the source/destination side actions.

        :param dnd_action:
            action selected by the compositor
        :type dnd_action:
            `ArgumentType.Uint`
        """
        self._post_event(2, dnd_action)


class WlDataSourceResource(Resource[WlDataSource]):
    interface = WlDataSource

    @WlDataSource.event(
        Argument(ArgumentType.String, nullable=True),
    )
    def target(self, mime_type: str | None) -> None:
        """A target accepts an offered mime type

        Sent when a target accepts pointer_focus or motion events.

        :param mime_type:
            mime type accepted by the target
        :type mime_type:
            `ArgumentType.String` or `None`
        """
        self._post_event(0, mime_type)

    @WlDataSource.event(
        Argument(ArgumentType.String),
        Argument(ArgumentType.FileDescriptor),
    )
    def send(self, mime_type: str, fd: int) -> None:
        """Send the data

        Request for data from the client.

        :param mime_type:
            mime type for the data
        :type mime_type:
            `ArgumentType.String`
        :param fd:
            file descriptor for the data to send
        :type fd:
            `ArgumentType.FileDescriptor`
        """
        self._post_event(1, mime_type, fd)

    @WlDataSource.event()
    def cancelled(self) -> None:
        """Selection was cancelled

        This data source is no longer valid.
        """
        self._post_event(2)

    @WlDataSource.event(version=3)
    def dnd_drop_performed(self) -> None:
        """The drag-and-drop operation physically finished

        The user performed the drop action.
        """
        self._post_event(3)

    @WlDataSource.event(version=3)
    def dnd_finished(self) -> None:
        """The drag-and-drop operation concluded

        The drop operation finished.
        """
        self._post_event(4)

    @WlDataSource.event(
        Argument(ArgumentType.Uint),
        version=3,
    )
    def action(self, dnd_action: int) -> None:
        """Notify the selected action

        This event indicates the action selected by the compositor.

        :param dnd_action:
            action selected by the compositor
        :type dnd_action:
            `ArgumentType.Uint`
        """
        self._post_event(5, dnd_action)


class WlDisplayResource(Resource[WlDisplay]):
    interface = WlDisplay

    @WlDisplay.event(
        Argument(ArgumentType.Object),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.String),
    )
    def error(self, object_id: object, code: int, message: str) -> None:
        """Fatal error event

        The error event is sent out to the client when a non-recoverable error
        has occurred.  The object_id argument is the object where the error
        occurred, most often in response to a request to that object.  The code
        identifies the error and is defined by the object interface.  As such,
        each interface defines its own set of error codes.  The meaning of the
        message is defined by the interface.

        :param object_id:
        :type object_id:
            `ArgumentType.Object`
        :param code:
            error code
        :type code:
            `ArgumentType.Uint`
        :param message:
            error message
        :type message:
            `ArgumentType.String`
        """
        self._post_event(0, object_id, code, message)

    @WlDisplay.event(
        Argument(ArgumentType.Uint),
    )
    def delete_id(self, id: int) -> None:
        """Acknowledge object id deletion

        This event is used internally by the object ID management logic.  When
        a client deletes an object that it had created, the server will send
        this event to acknowledge that it has seen the delete request.  When
        the client receives this event, it will know that it can safely reuse
        the object ID.

        :param id:
            deleted object ID
        :type id:
            `ArgumentType.Uint`
        """
        self._post_event(1, id)


class WlKeyboardResource(Resource[WlKeyboard]):
    interface = WlKeyboard

    @WlKeyboard.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.FileDescriptor),
        Argument(ArgumentType.Uint),
    )
    def keymap(self, format: int, fd: int, size: int) -> None:
        """Keyboard mapping

        This event provides a file descriptor to the client which can be
        memory-mapped to provide a keyboard mapping description.

        :param format:
            keymap format
        :type format:
            `ArgumentType.Uint`
        :param fd:
            keymap file descriptor
        :type fd:
            `ArgumentType.FileDescriptor`
        :param size:
            keymap size, in bytes
        :type size:
            `ArgumentType.Uint`
        """
        self._post_event(0, format, fd, size)

    @WlKeyboard.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlSurface),
        Argument(ArgumentType.Array),
    )
    def enter(self, serial: int, surface: WlSurface, keys: list) -> None:
        """Enter event

        Notification that this seat's keyboard focus is on a certain surface.

        :param serial:
            serial number of the enter event
        :type serial:
            `ArgumentType.Uint`
        :param surface:
            surface gaining keyboard focus
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :param keys:
            the currently pressed keys
        :type keys:
            `ArgumentType.Array`
        """
        self._post_event(1, serial, surface, keys)

    @WlKeyboard.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlSurface),
    )
    def leave(self, serial: int, surface: WlSurface) -> None:
        """Leave event

        Notification that this seat's keyboard focus is no longer on a certain
        surface.

        :param serial:
            serial number of the leave event
        :type serial:
            `ArgumentType.Uint`
        :param surface:
            surface that lost keyboard focus
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        """
        self._post_event(2, serial, surface)

    @WlKeyboard.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def key(self, serial: int, time: int, key: int, state: int) -> None:
        """Key event

        A key was pressed or released.

        :param serial:
            serial number of the key event
        :type serial:
            `ArgumentType.Uint`
        :param time:
            timestamp with millisecond granularity
        :type time:
            `ArgumentType.Uint`
        :param key:
            key that produced the event
        :type key:
            `ArgumentType.Uint`
        :param state:
            physical state of the key
        :type state:
            `ArgumentType.Uint`
        """
        self._post_event(3, serial, time, key, state)

    @WlKeyboard.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def modifiers(self, serial: int, mods_depressed: int, mods_latched: int, mods_locked: int, group: int) -> None:
        """Modifier and group state

        Notifies clients that the modifier and/or group state has changed.

        :param serial:
            serial number of the modifiers event
        :type serial:
            `ArgumentType.Uint`
        :param mods_depressed:
            depressed modifiers
        :type mods_depressed:
            `ArgumentType.Uint`
        :param mods_latched:
            latched modifiers
        :type mods_latched:
            `ArgumentType.Uint`
        :param mods_locked:
            locked modifiers
        :type mods_locked:
            `ArgumentType.Uint`
        :param group:
            keyboard layout
        :type group:
            `ArgumentType.Uint`
        """
        self._post_event(4, serial, mods_depressed, mods_latched, mods_locked, group)

    @WlKeyboard.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        version=4,
    )
    def repeat_info(self, rate: int, delay: int) -> None:
        """Repeat rate and delay

        Informs the client about the keyboard's repeat rate and delay.

        :param rate:
            the rate of repeating keys in characters per second
        :type rate:
            `ArgumentType.Int`
        :param delay:
            delay in milliseconds before a repeating key starts repeating
        :type delay:
            `ArgumentType.Int`
        """
        self._post_event(5, rate, delay)


class WlOutputResource(Resource[WlOutput]):
    interface = WlOutput

    @WlOutput.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.String),
        Argument(ArgumentType.String),
        Argument(ArgumentType.Int),
    )
    def geometry(self, x: int, y: int, physical_width: int, physical_height: int, subpixel: int, make: str, model: str, transform: int) -> None:
        """Properties of the output

        The geometry event describes geometric properties of the output.

        :param x:
            x position within the global compositor space
        :type x:
            `ArgumentType.Int`
        :param y:
            y position within the global compositor space
        :type y:
            `ArgumentType.Int`
        :param physical_width:
            width in millimeters of the output
        :type physical_width:
            `ArgumentType.Int`
        :param physical_height:
            height in millimeters of the output
        :type physical_height:
            `ArgumentType.Int`
        :param subpixel:
            subpixel orientation of the output
        :type subpixel:
            `ArgumentType.Int`
        :param make:
            textual description of the manufacturer
        :type make:
            `ArgumentType.String`
        :param model:
            textual description of the model
        :type model:
            `ArgumentType.String`
        :param transform:
            transform that maps framebuffer to output
        :type transform:
            `ArgumentType.Int`
        """
        self._post_event(0, x, y, physical_width, physical_height, subpixel, make, model, transform)

    @WlOutput.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def mode(self, flags: int, width: int, height: int, refresh: int) -> None:
        """Advertise available modes for the output

        The mode event describes an available mode for the output.

        :param flags:
            bitfield of mode flags
        :type flags:
            `ArgumentType.Uint`
        :param width:
            width of the mode in hardware units
        :type width:
            `ArgumentType.Int`
        :param height:
            height of the mode in hardware units
        :type height:
            `ArgumentType.Int`
        :param refresh:
            vertical refresh rate in mHz
        :type refresh:
            `ArgumentType.Int`
        """
        self._post_event(1, flags, width, height, refresh)

    @WlOutput.event()
    def done(self) -> None:
        """Sent all information about output

        This event is sent after all other properties have been sent after
        binding to the output object.
        """
        self._post_event(2)

    @WlOutput.event(
        Argument(ArgumentType.Int),
        version=2,
    )
    def scale(self, factor: int) -> None:
        """Output scale properties

        This event contains scaling factor information.

        :param factor:
            scaling factor of output
        :type factor:
            `ArgumentType.Int`
        """
        self._post_event(3, factor)

    @WlOutput.event(
        Argument(ArgumentType.String),
        version=4,
    )
    def name(self, name: str) -> None:
        """Name of this output

        The name is a UTF-8 string with no convention defined for its contents.

        :param name:
            output name
        :type name:
            `ArgumentType.String`
        """
        self._post_event(4, name)

    @WlOutput.event(
        Argument(ArgumentType.String),
        version=4,
    )
    def description(self, description: str) -> None:
        """Human-readable description of this output

        This is a UTF-8 string.

        :param description:
            output description
        :type description:
            `ArgumentType.String`
        """
        self._post_event(5, description)


class WlPointerResource(Resource[WlPointer]):
    interface = WlPointer

    @WlPointer.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlSurface),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Fixed),
    )
    def enter(self, serial: int, surface: WlSurface, surface_x: float, surface_y: float) -> None:
        """Pointer entered a surface

        The enter event is sent to the client when the pointer enters the
        surface.

        :param serial:
            serial number of the enter event
        :type serial:
            `ArgumentType.Uint`
        :param surface:
            surface entered by the pointer
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :param surface_x:
            surface-local x coordinate
        :type surface_x:
            `ArgumentType.Fixed`
        :param surface_y:
            surface-local y coordinate
        :type surface_y:
            `ArgumentType.Fixed`
        """
        self._post_event(0, serial, surface, surface_x, surface_y)

    @WlPointer.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlSurface),
    )
    def leave(self, serial: int, surface: WlSurface) -> None:
        """Pointer left a surface

        The leave event is sent to the client when the pointer leaves the
        surface.

        :param serial:
            serial number of the leave event
        :type serial:
            `ArgumentType.Uint`
        :param surface:
            surface left by the pointer
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        """
        self._post_event(1, serial, surface)

    @WlPointer.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Fixed),
    )
    def motion(self, time: int, surface_x: float, surface_y: float) -> None:
        """Pointer motion event

        The motion event is sent to the client when the pointer moves.

        :param time:
            timestamp with millisecond granularity
        :type time:
            `ArgumentType.Uint`
        :param surface_x:
            surface-local x coordinate
        :type surface_x:
            `ArgumentType.Fixed`
        :param surface_y:
            surface-local y coordinate
        :type surface_y:
            `ArgumentType.Fixed`
        """
        self._post_event(2, time, surface_x, surface_y)

    @WlPointer.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def button(self, serial: int, time: int, button: int, state: int) -> None:
        """Pointer button event

        The button event is sent to the client when a button press or release
        is detected.

        :param serial:
            serial number of the button event
        :type serial:
            `ArgumentType.Uint`
        :param time:
            timestamp with millisecond granularity
        :type time:
            `ArgumentType.Uint`
        :param button:
            button that produced the event
        :type button:
            `ArgumentType.Uint`
        :param state:
            physical state of the button
        :type state:
            `ArgumentType.Uint`
        """
        self._post_event(3, serial, time, button, state)

    @WlPointer.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Fixed),
    )
    def axis(self, time: int, axis: int, value: float) -> None:
        """Axis change event

        The axis event is sent when the pointer's scroll wheel or other axis is
        moved.

        :param time:
            timestamp with millisecond granularity
        :type time:
            `ArgumentType.Uint`
        :param axis:
            axis type
        :type axis:
            `ArgumentType.Uint`
        :param value:
            length of vector in surface-local coordinate space
        :type value:
            `ArgumentType.Fixed`
        """
        self._post_event(4, time, axis, value)

    @WlPointer.event(version=5)
    def frame(self) -> None:
        """End of a pointer event sequence

        Indicates the end of a set of events that logically belong together.
        """
        self._post_event(5)

    @WlPointer.event(
        Argument(ArgumentType.Uint),
        version=5,
    )
    def axis_source(self, axis_source: int) -> None:
        """Axis source event

        Source information for scroll events.

        :param axis_source:
            source of the axis event
        :type axis_source:
            `ArgumentType.Uint`
        """
        self._post_event(6, axis_source)

    @WlPointer.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        version=5,
    )
    def axis_stop(self, time: int, axis: int) -> None:
        """Axis stop event

        Stop notification for scroll events.

        :param time:
            timestamp with millisecond granularity
        :type time:
            `ArgumentType.Uint`
        :param axis:
            axis type
        :type axis:
            `ArgumentType.Uint`
        """
        self._post_event(7, time, axis)

    @WlPointer.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Int),
        version=5,
    )
    def axis_discrete(self, axis: int, discrete: int) -> None:
        """Axis click event

        Discrete step information for scroll events.

        :param axis:
            axis type
        :type axis:
            `ArgumentType.Uint`
        :param discrete:
            number of steps
        :type discrete:
            `ArgumentType.Int`
        """
        self._post_event(8, axis, discrete)


class WlRegionResource(Resource[WlRegion]):
    interface = WlRegion


class WlRegistryResource(Resource[WlRegistry]):
    interface = WlRegistry

    @WlRegistry.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.String),
        Argument(ArgumentType.Uint),
    )
    def global_(self, name: int, interface: str, version: int) -> None:
        """Announce global object

        Notify the client of global objects.

        The event notifies the client that a global object with the given name
        is now available, and it provides the high-level interface name.  The
        name can be used to request the global object later.

        :param name:
            numeric name of the global object
        :type name:
            `ArgumentType.Uint`
        :param interface:
            interface implemented by the object
        :type interface:
            `ArgumentType.String`
        :param version:
            interface version
        :type version:
            `ArgumentType.Uint`
        """
        self._post_event(0, name, interface, version)

    @WlRegistry.event(
        Argument(ArgumentType.Uint),
    )
    def global_remove(self, name: int) -> None:
        """Announce removal of global object

        Notify the client of removed global objects.

        This event notifies the client that the global identified by name is no
        longer available.  If the client bound to the global using the bind
        request, the client should now destroy that object.

        :param name:
            numeric name of the global object
        :type name:
            `ArgumentType.Uint`
        """
        self._post_event(1, name)


class WlSeatResource(Resource[WlSeat]):
    interface = WlSeat

    @WlSeat.event(
        Argument(ArgumentType.Uint),
    )
    def capabilities(self, capabilities: int) -> None:
        """Seat capabilities changed

        This is emitted whenever a seat gains or loses the pointer, keyboard or
        touch capabilities.

        :param capabilities:
            capabilities of the seat
        :type capabilities:
            `ArgumentType.Uint`
        """
        self._post_event(0, capabilities)

    @WlSeat.event(
        Argument(ArgumentType.String),
        version=2,
    )
    def name(self, name: str) -> None:
        """Unique identifier for this seat

        In a multiseat configuration this can be used to distinguish different
        seats.

        :param name:
            seat identifier
        :type name:
            `ArgumentType.String`
        """
        self._post_event(1, name)


class WlShellResource(Resource[WlShell]):
    interface = WlShell


class WlShellSurfaceResource(Resource[WlShellSurface]):
    interface = WlShellSurface

    @WlShellSurface.event(
        Argument(ArgumentType.Uint),
    )
    def ping(self, serial: int) -> None:
        """Ping client

        Ping a client to check it is responding.

        :param serial:
            serial number of the ping
        :type serial:
            `ArgumentType.Uint`
        """
        self._post_event(0, serial)

    @WlShellSurface.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def configure(self, edges: int, width: int, height: int) -> None:
        """Suggest resize

        The configure event asks the client to resize its surface.

        :param edges:
            how the surface was resized
        :type edges:
            `ArgumentType.Uint`
        :param width:
            new width of the surface
        :type width:
            `ArgumentType.Int`
        :param height:
            new height of the surface
        :type height:
            `ArgumentType.Int`
        """
        self._post_event(1, edges, width, height)

    @WlShellSurface.event()
    def popup_done(self) -> None:
        """Popup interaction is done

        The popup_done event is sent out when a popup grab is broken, that is,
        when the user clicks a surface that doesn't belong to the client owning
        the popup surface.
        """
        self._post_event(2)


class WlShmResource(Resource[WlShm]):
    interface = WlShm


class WlShmPoolResource(Resource[WlShmPool]):
    interface = WlShmPool


class WlSubcompositorResource(Resource[WlSubcompositor]):
    interface = WlSubcompositor


class WlSubsurfaceResource(Resource[WlSubsurface]):
    interface = WlSubsurface


class WlSurfaceResource(Resource[WlSurface]):
    interface = WlSurface

    @WlSurface.event(
        Argument(ArgumentType.Object, interface=WlOutput),
    )
    def enter(self, output: WlOutput) -> None:
        """Surface enters an output

        This is emitted whenever a surface's creation, movement, or resizing
        results in some part of it being within the region of an output.

        :param output:
            output entered by the surface
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput`
        """
        self._post_event(0, output)

    @WlSurface.event(
        Argument(ArgumentType.Object, interface=WlOutput),
    )
    def leave(self, output: WlOutput) -> None:
        """Surface leaves an output

        This is emitted whenever a surface's creation, movement, or resizing
        results in it no longer having any part of it within the region of an
        output.

        :param output:
            output left by the surface
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput`
        """
        self._post_event(1, output)


class WlTouchResource(Resource[WlTouch]):
    interface = WlTouch

    @WlTouch.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlSurface),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Fixed),
    )
    def down(self, serial: int, time: int, surface: WlSurface, id: int, x: float, y: float) -> None:
        """Touch down event and beginning of a touch sequence

        A new touch point has appeared on the surface.

        :param serial:
            serial number of the touch down event
        :type serial:
            `ArgumentType.Uint`
        :param time:
            timestamp with millisecond granularity
        :type time:
            `ArgumentType.Uint`
        :param surface:
            surface touched
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :param id:
            the unique ID of this touch point
        :type id:
            `ArgumentType.Int`
        :param x:
            surface-local x coordinate
        :type x:
            `ArgumentType.Fixed`
        :param y:
            surface-local y coordinate
        :type y:
            `ArgumentType.Fixed`
        """
        self._post_event(0, serial, time, surface, id, x, y)

    @WlTouch.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Int),
    )
    def up(self, serial: int, time: int, id: int) -> None:
        """End of a touch event sequence

        The touch point has disappeared.

        :param serial:
            serial number of the touch up event
        :type serial:
            `ArgumentType.Uint`
        :param time:
            timestamp with millisecond granularity
        :type time:
            `ArgumentType.Uint`
        :param id:
            the unique ID of this touch point
        :type id:
            `ArgumentType.Int`
        """
        self._post_event(1, serial, time, id)

    @WlTouch.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Fixed),
    )
    def motion(self, time: int, id: int, x: float, y: float) -> None:
        """Update of touch point

        A touch point has changed coordinates.

        :param time:
            timestamp with millisecond granularity
        :type time:
            `ArgumentType.Uint`
        :param id:
            the unique ID of this touch point
        :type id:
            `ArgumentType.Int`
        :param x:
            surface-local x coordinate
        :type x:
            `ArgumentType.Fixed`
        :param y:
            surface-local y coordinate
        :type y:
            `ArgumentType.Fixed`
        """
        self._post_event(2, time, id, x, y)

    @WlTouch.event()
    def frame(self) -> None:
        """End of touch frame

        Indicates the end of a set of events that belong together.
        """
        self._post_event(3)

    @WlTouch.event()
    def cancel(self) -> None:
        """Touch session cancelled

        Sent if the compositor decides the touch stream is a global gesture.
        """
        self._post_event(4)

    @WlTouch.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Fixed),
        version=6,
    )
    def shape(self, id: int, major: float, minor: float) -> None:
        """Update shape of touch point

        Sent when a touchpoint has changed its shape.

        :param id:
            the unique ID of this touch point
        :type id:
            `ArgumentType.Int`
        :param major:
            length of the major axis of the ellipse
        :type major:
            `ArgumentType.Fixed`
        :param minor:
            length of the minor axis of the ellipse
        :type minor:
            `ArgumentType.Fixed`
        """
        self._post_event(5, id, major, minor)

    @WlTouch.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Fixed),
        version=6,
    )
    def orientation(self, id: int, orientation: float) -> None:
        """Update orientation of touch point

        Sent when a touchpoint has changed its orientation.

        :param id:
            the unique ID of this touch point
        :type id:
            `ArgumentType.Int`
        :param orientation:
            angle between the major axis and the positive surface y-axis
        :type orientation:
            `ArgumentType.Fixed`
        """
        self._post_event(6, id, orientation)


class WlBufferProxy(Proxy[WlBuffer]):
    interface = WlBuffer

    @WlBuffer.request()
    def destroy(self) -> None:
        """Destroy a buffer

        Destroy a buffer. If and how you need to release the underlying storage
        is defined by the buffer factory interface.
        """
        self._marshal(0)


class WlCallbackProxy(Proxy[WlCallback]):
    interface = WlCallback


class WlCompositorProxy(Proxy[WlCompositor]):
    interface = WlCompositor

    @WlCompositor.request(
        Argument(ArgumentType.NewId, interface=WlSurface),
    )
    def create_surface(self) -> WlSurfaceProxy:
        """Create new surface

        Ask the compositor to create a new surface.

        :returns:
            :class:`~pywayland.protocol.wayland.WlSurface` -- the new surface
        """
        id = self._marshal_constructor(0, WlSurface)
        return id

    @WlCompositor.request(
        Argument(ArgumentType.NewId, interface=WlRegion),
    )
    def create_region(self) -> WlRegionProxy:
        """Create new region

        Ask the compositor to create a new region.

        :returns:
            :class:`~pywayland.protocol.wayland.WlRegion` -- the new region
        """
        id = self._marshal_constructor(1, WlRegion)
        return id


class WlDataDeviceProxy(Proxy[WlDataDevice]):
    interface = WlDataDevice

    @WlDataDevice.request(
        Argument(ArgumentType.Object, interface=WlDataSource, nullable=True),
        Argument(ArgumentType.Object, interface=WlSurface),
        Argument(ArgumentType.Object, interface=WlSurface, nullable=True),
        Argument(ArgumentType.Uint),
    )
    def start_drag(self, source: WlDataSourceProxy | None, origin: WlSurfaceProxy, icon: WlSurfaceProxy | None, serial: int) -> None:
        """Start drag-and-drop operation

        This request asks the compositor to start a drag-and-drop operation on
        behalf of the client.

        :param source:
            data source for the drag
        :type source:
            :class:`~pywayland.protocol.wayland.WlDataSource` or `None`
        :param origin:
            surface where the drag originates
        :type origin:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :param icon:
            drag-and-drop icon surface
        :type icon:
            :class:`~pywayland.protocol.wayland.WlSurface` or `None`
        :param serial:
            serial number of the implicit grab on the pointer
        :type serial:
            `ArgumentType.Uint`
        """
        self._marshal(0, source, origin, icon, serial)

    @WlDataDevice.request(
        Argument(ArgumentType.Object, interface=WlDataSource, nullable=True),
        Argument(ArgumentType.Uint),
    )
    def set_selection(self, source: WlDataSourceProxy | None, serial: int) -> None:
        """Copy data to the selection

        This request asks the compositor to set the selection to the data from
        the source on behalf of the client.

        :param source:
            data source for the selection
        :type source:
            :class:`~pywayland.protocol.wayland.WlDataSource` or `None`
        :param serial:
            serial number of the event that triggered this request
        :type serial:
            `ArgumentType.Uint`
        """
        self._marshal(1, source, serial)

    @WlDataDevice.request(version=2)
    def release(self) -> None:
        """Destroy data device

        This request destroys the data device.
        """
        self._marshal(2)


class WlDataDeviceManagerProxy(Proxy[WlDataDeviceManager]):
    interface = WlDataDeviceManager

    @WlDataDeviceManager.request(
        Argument(ArgumentType.NewId, interface=WlDataSource),
    )
    def create_data_source(self) -> WlDataSourceProxy:
        """Create a new data source

        Create a new data source.

        :returns:
            :class:`~pywayland.protocol.wayland.WlDataSource` -- data source to
            create
        """
        id = self._marshal_constructor(0, WlDataSource)
        return id

    @WlDataDeviceManager.request(
        Argument(ArgumentType.NewId, interface=WlDataDevice),
        Argument(ArgumentType.Object, interface=WlSeat),
    )
    def get_data_device(self, seat: WlSeatProxy) -> WlDataDeviceProxy:
        """Create a new data device

        Create a new data device for a given seat.

        :param seat:
            seat associated with the data device
        :type seat:
            :class:`~pywayland.protocol.wayland.WlSeat`
        :returns:
            :class:`~pywayland.protocol.wayland.WlDataDevice` -- data device to
            create
        """
        id = self._marshal_constructor(1, WlDataDevice, seat)
        return id


class WlDataOfferProxy(Proxy[WlDataOffer]):
    interface = WlDataOffer

    @WlDataOffer.request(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.String, nullable=True),
    )
    def accept(self, serial: int, mime_type: str | None) -> None:
        """Accept one of the offered mime types

        Indicate that the client accepts :class:`WlDataOffer` of the given
        type, or NULL if not accepted.

        :param serial:
            serial number of the accept request
        :type serial:
            `ArgumentType.Uint`
        :param mime_type:
            mime type accepted by the client
        :type mime_type:
            `ArgumentType.String` or `None`
        """
        self._marshal(0, serial, mime_type)

    @WlDataOffer.request(
        Argument(ArgumentType.String),
        Argument(ArgumentType.FileDescriptor),
    )
    def receive(self, mime_type: str, fd: int) -> None:
        """Request that the data be transferred

        To transfer the offered data, the client issues this request and
        indicates the mime type it wants to receive.  The transfer happens
        through the passed file descriptor (typically created with the pipe
        system call).  The source client writes the data in the mime type
        representation requested and then closes the file descriptor.

        :param mime_type:
            mime type desired by receiver
        :type mime_type:
            `ArgumentType.String`
        :param fd:
            file descriptor for data transfer
        :type fd:
            `ArgumentType.FileDescriptor`
        """
        self._marshal(1, mime_type, fd)

    @WlDataOffer.request()
    def destroy(self) -> None:
        """Destroy data offer

        Destroy the data offer.
        """
        self._marshal(2)

    @WlDataOffer.request(version=3)
    def finish(self) -> None:
        """The offer will no longer be used

        Notifies the compositor that the drag destination successfully finished
        the drag operation.
        """
        self._marshal(3)

    @WlDataOffer.request(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        version=3,
    )
    def set_actions(self, dnd_actions: int, preferred_action: int) -> None:
        """Set the available/preferred drag-and-drop actions

        Sets the actions that the destination side client supports for this
        operation. This request should only be made by clients that support
        drag-and-drop actions.

        :param dnd_actions:
            actions supported by the destination client
        :type dnd_actions:
            `ArgumentType.Uint`
        :param preferred_action:
            action preferred by the destination client
        :type preferred_action:
            `ArgumentType.Uint`
        """
        self._marshal(4, dnd_actions, preferred_action)


class WlDataSourceProxy(Proxy[WlDataSource]):
    interface = WlDataSource

    @WlDataSource.request(
        Argument(ArgumentType.String),
    )
    def offer(self, mime_type: str) -> None:
        """Add an offered mime type

        This request adds a mime type to the set of mime types advertised to
        targets.

        :param mime_type:
            mime type offered by the data source
        :type mime_type:
            `ArgumentType.String`
        """
        self._marshal(0, mime_type)

    @WlDataSource.request()
    def destroy(self) -> None:
        """Destroy the data source

        Destroy the data source.
        """
        self._marshal(1)


class WlDisplayProxy(Proxy[WlDisplay]):
    interface = WlDisplay

    @WlDisplay.request(
        Argument(ArgumentType.NewId, interface=WlCallback),
    )
    def sync(self) -> WlCallbackProxy:
        """Asynchronous roundtrip

        The sync request asks the server to emit the 'done' event on the
        returned :class:`~pywayland.protocol.wayland.WlCallback` object.  Since
        requests are handled in-order and events are delivered in-order, this
        can be used as a barrier to ensure all previous requests to the server
        have been processed.

        The object returned by this request will be destroyed by the compositor
        after the callback is fired and as such the client must not attempt to
        use it after that point.

        The callback_data passed in the callback is the event serial.

        :returns:
            :class:`~pywayland.protocol.wayland.WlCallback` -- callback object
            for the sync request
        """
        callback = self._marshal_constructor(0, WlCallback)
        return callback

    @WlDisplay.request(
        Argument(ArgumentType.NewId, interface=WlRegistry),
    )
    def get_registry(self) -> WlRegistryProxy:
        """Get global registry object

        This request creates a registry object that allows the client to list
        the global objects available from the compositor.

        It should be noted that the server side resources consumed by this
        request should be released immediately when the client is done with
        them.

        :returns:
            :class:`~pywayland.protocol.wayland.WlRegistry` -- global registry
            object
        """
        registry = self._marshal_constructor(1, WlRegistry)
        return registry


class WlKeyboardProxy(Proxy[WlKeyboard]):
    interface = WlKeyboard

    @WlKeyboard.request(version=3)
    def release(self) -> None:
        """Release the keyboard object
        """
        self._marshal(0)


class WlOutputProxy(Proxy[WlOutput]):
    interface = WlOutput

    @WlOutput.request(version=3)
    def release(self) -> None:
        """Release the output object

        Using this request a client can tell the server that it is not going to
        use the output object anymore.
        """
        self._marshal(0)


class WlPointerProxy(Proxy[WlPointer]):
    interface = WlPointer

    @WlPointer.request(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlSurface, nullable=True),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def set_cursor(self, serial: int, surface: WlSurfaceProxy | None, hotspot_x: int, hotspot_y: int) -> None:
        """Set the pointer surface

        Set the pointer surface, i.e., the surface that contains the pointer
        image (cursor).

        :param serial:
            serial number of the enter event
        :type serial:
            `ArgumentType.Uint`
        :param surface:
            pointer surface
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface` or `None`
        :param hotspot_x:
            surface-local x coordinate
        :type hotspot_x:
            `ArgumentType.Int`
        :param hotspot_y:
            surface-local y coordinate
        :type hotspot_y:
            `ArgumentType.Int`
        """
        self._marshal(0, serial, surface, hotspot_x, hotspot_y)

    @WlPointer.request(version=3)
    def release(self) -> None:
        """Release the pointer object

        Using this request a client can tell the server that it is not going to
        use the pointer object anymore.
        """
        self._marshal(1)


class WlRegionProxy(Proxy[WlRegion]):
    interface = WlRegion

    @WlRegion.request()
    def destroy(self) -> None:
        """Destroy region

        Destroy the region.  This will invalidate the object ID.
        """
        self._marshal(0)

    @WlRegion.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def add(self, x: int, y: int, width: int, height: int) -> None:
        """Add rectangle to region

        Add the specified rectangle to the region.

        :param x:
            region-local x coordinate
        :type x:
            `ArgumentType.Int`
        :param y:
            region-local y coordinate
        :type y:
            `ArgumentType.Int`
        :param width:
            rectangle width
        :type width:
            `ArgumentType.Int`
        :param height:
            rectangle height
        :type height:
            `ArgumentType.Int`
        """
        self._marshal(1, x, y, width, height)

    @WlRegion.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def subtract(self, x: int, y: int, width: int, height: int) -> None:
        """Subtract rectangle from region

        Subtract the specified rectangle from the region.

        :param x:
            region-local x coordinate
        :type x:
            `ArgumentType.Int`
        :param y:
            region-local y coordinate
        :type y:
            `ArgumentType.Int`
        :param width:
            rectangle width
        :type width:
            `ArgumentType.Int`
        :param height:
            rectangle height
        :type height:
            `ArgumentType.Int`
        """
        self._marshal(2, x, y, width, height)


class WlRegistryProxy(Proxy[WlRegistry]):
    interface = WlRegistry

    @WlRegistry.request(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.NewId),
    )
    def bind(self, name: int, interface: type[Interface], version: int) -> Any:
        """Bind an object to the display

        Binds a new, client-created object to the server using the specified
        name as the identifier.

        :param name:
            unique numeric name of the object
        :type name:
            `ArgumentType.Uint`
        :param interface:
            Interface name
        :type interface:
            `string`
        :param version:
            Interface version
        :type version:
            `int`
        :returns:
            :class:`pywayland.client.proxy.Proxy` of specified Interface --
            bounded object
        """
        id = self._marshal_constructor(0, interface, name, interface.name, version)
        return id


class WlSeatProxy(Proxy[WlSeat]):
    interface = WlSeat

    @WlSeat.request(
        Argument(ArgumentType.NewId, interface=WlPointer),
    )
    def get_pointer(self) -> WlPointerProxy:
        """Return pointer object

        The ID provided will be initialized to the
        :class:`~pywayland.protocol.wayland.WlPointer` interface for this seat.

        :returns:
            :class:`~pywayland.protocol.wayland.WlPointer` -- seat pointer
        """
        id = self._marshal_constructor(0, WlPointer)
        return id

    @WlSeat.request(
        Argument(ArgumentType.NewId, interface=WlKeyboard),
    )
    def get_keyboard(self) -> WlKeyboardProxy:
        """Return keyboard object

        The ID provided will be initialized to the
        :class:`~pywayland.protocol.wayland.WlKeyboard` interface for this
        seat.

        :returns:
            :class:`~pywayland.protocol.wayland.WlKeyboard` -- seat keyboard
        """
        id = self._marshal_constructor(1, WlKeyboard)
        return id

    @WlSeat.request(
        Argument(ArgumentType.NewId, interface=WlTouch),
    )
    def get_touch(self) -> WlTouchProxy:
        """Return touch object

        The ID provided will be initialized to the
        :class:`~pywayland.protocol.wayland.WlTouch` interface for this seat.

        :returns:
            :class:`~pywayland.protocol.wayland.WlTouch` -- seat touch
            interface
        """
        id = self._marshal_constructor(2, WlTouch)
        return id

    @WlSeat.request(version=5)
    def release(self) -> None:
        """Release the seat object

        Using this request a client can tell the server that it is not going to
        use the seat object anymore.
        """
        self._marshal(3)


class WlShellProxy(Proxy[WlShell]):
    interface = WlShell

    @WlShell.request(
        Argument(ArgumentType.NewId, interface=WlShellSurface),
        Argument(ArgumentType.Object, interface=WlSurface),
    )
    def get_shell_surface(self, surface: WlSurfaceProxy) -> WlShellSurfaceProxy:
        """Create a shell surface from a surface

        Create a shell surface for an existing surface.

        :param surface:
            surface to be given the shell surface interface
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :returns:
            :class:`~pywayland.protocol.wayland.WlShellSurface` -- shell
            surface to create
        """
        id = self._marshal_constructor(0, WlShellSurface, surface)
        return id


class WlShellSurfaceProxy(Proxy[WlShellSurface]):
    interface = WlShellSurface

    @WlShellSurface.request(
        Argument(ArgumentType.Uint),
    )
    def ping(self, serial: int) -> None:
        """Ping the surface

        Ping a surface to keep it alive.

        :param serial:
            serial number of the ping
        :type serial:
            `ArgumentType.Uint`
        """
        self._marshal(0, serial)

    @WlShellSurface.request()
    def set_toplevel(self) -> None:
        """Set surface as a toplevel

        Map the surface as a toplevel surface.
        """
        self._marshal(1)

    @WlShellSurface.request(
        Argument(ArgumentType.Object, interface=WlSurface),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Uint),
    )
    def set_transient(self, parent: WlSurfaceProxy, x: int, y: int, flags: int) -> None:
        """Set the surface as a transient

        Map the surface relative to an existing surface.

        :param parent:
            parent surface
        :type parent:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :param x:
            surface-local x coordinate
        :type x:
            `ArgumentType.Int`
        :param y:
            surface-local y coordinate
        :type y:
            `ArgumentType.Int`
        :param flags:
            transient surface mapping flags
        :type flags:
            `ArgumentType.Uint`
        """
        self._marshal(2, parent, x, y, flags)

    @WlShellSurface.request(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlOutput, nullable=True),
    )
    def set_fullscreen(self, method: int, framerate: int, output: WlOutputProxy | None) -> None:
        """Set the surface as fullscreen

        Map the surface as a fullscreen surface.

        :param method:
            fullscreen method
        :type method:
            `ArgumentType.Uint`
        :param framerate:
            framerate in mHz
        :type framerate:
            `ArgumentType.Uint`
        :param output:
            output on which the surface is to be fullscreen
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput` or `None`
        """
        self._marshal(3, method, framerate, output)

    @WlShellSurface.request(
        Argument(ArgumentType.Object, interface=WlSeat),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlSurface),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Uint),
    )
    def set_popup(self, seat: WlSeatProxy, serial: int, parent: WlSurfaceProxy, x: int, y: int, flags: int) -> None:
        """Set the surface as popup

        Map the surface as a popup.

        :param seat:
            seat whose pointer is used
        :type seat:
            :class:`~pywayland.protocol.wayland.WlSeat`
        :param serial:
            serial number of the implicit grab on the pointer
        :type serial:
            `ArgumentType.Uint`
        :param parent:
            parent surface
        :type parent:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :param x:
            surface-local x coordinate
        :type x:
            `ArgumentType.Int`
        :param y:
            surface-local y coordinate
        :type y:
            `ArgumentType.Int`
        :param flags:
            transient surface mapping flags
        :type flags:
            `ArgumentType.Uint`
        """
        self._marshal(4, seat, serial, parent, x, y, flags)

    @WlShellSurface.request(
        Argument(ArgumentType.Object, interface=WlOutput, nullable=True),
    )
    def set_maximized(self, output: WlOutputProxy | None) -> None:
        """Set the surface as maximized

        Map the surface as a maximized surface.

        :param output:
            output on which the surface is to be maximized
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput` or `None`
        """
        self._marshal(5, output)


class WlShmProxy(Proxy[WlShm]):
    interface = WlShm

    @WlShm.request(
        Argument(ArgumentType.NewId, interface=WlShmPool),
        Argument(ArgumentType.FileDescriptor),
        Argument(ArgumentType.Int),
    )
    def create_pool(self, fd: int, size: int) -> WlShmPoolProxy:
        """Create a shm pool

        Create a new :class:`~pywayland.protocol.wayland.WlShmPool` object.

        :param fd:
            file descriptor for the pool
        :type fd:
            `ArgumentType.FileDescriptor`
        :param size:
            pool size, in bytes
        :type size:
            `ArgumentType.Int`
        :returns:
            :class:`~pywayland.protocol.wayland.WlShmPool` -- pool to create
        """
        id = self._marshal_constructor(0, WlShmPool, fd, size)
        return id


class WlShmPoolProxy(Proxy[WlShmPool]):
    interface = WlShmPool

    @WlShmPool.request(
        Argument(ArgumentType.NewId, interface=WlBuffer),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Uint),
    )
    def create_buffer(self, offset: int, width: int, height: int, stride: int, format: int) -> WlBufferProxy:
        """Create a buffer from the pool

        Create a :class:`~pywayland.protocol.wayland.WlBuffer` object from the
        pool.

        :param offset:
            buffer byte offset within the pool
        :type offset:
            `ArgumentType.Int`
        :param width:
            buffer width, in pixels
        :type width:
            `ArgumentType.Int`
        :param height:
            buffer height, in pixels
        :type height:
            `ArgumentType.Int`
        :param stride:
            number of bytes from the beginning of one row to the beginning of
            the next row, including padding
        :type stride:
            `ArgumentType.Int`
        :param format:
            buffer pixel format
        :type format:
            `ArgumentType.Uint`
        :returns:
            :class:`~pywayland.protocol.wayland.WlBuffer` -- buffer to create
        """
        id = self._marshal_constructor(0, WlBuffer, offset, width, height, stride, format)
        return id

    @WlShmPool.request()
    def destroy(self) -> None:
        """Destroy the pool

        Destroy the shared memory pool.
        """
        self._marshal(1)

    @WlShmPool.request(
        Argument(ArgumentType.Int),
    )
    def resize(self, size: int) -> None:
        """Alter the pool size

        Used to shrink the pool.

        :param size:
            new size of the pool, in bytes
        :type size:
            `ArgumentType.Int`
        """
        self._marshal(2, size)


class WlSubcompositorProxy(Proxy[WlSubcompositor]):
    interface = WlSubcompositor

    @WlSubcompositor.request()
    def destroy(self) -> None:
        """Unbind from the subcompositor interface

        Informs the server that the client will not be using this protocol
        object anymore.
        """
        self._marshal(0)

    @WlSubcompositor.request(
        Argument(ArgumentType.NewId, interface=WlSubsurface),
        Argument(ArgumentType.Object, interface=WlSurface),
        Argument(ArgumentType.Object, interface=WlSurface),
    )
    def get_subsurface(self, surface: WlSurfaceProxy, parent: WlSurfaceProxy) -> WlSubsurfaceProxy:
        """Introduce a sub-surface interface for a surface

        Create a sub-surface interface for the given surface.

        :param surface:
            the surface to manage
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :param parent:
            the parent surface
        :type parent:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :returns:
            :class:`~pywayland.protocol.wayland.WlSubsurface` -- the new sub-
            surface object ID
        """
        id = self._marshal_constructor(1, WlSubsurface, surface, parent)
        return id


class WlSubsurfaceProxy(Proxy[WlSubsurface]):
    interface = WlSubsurface

    @WlSubsurface.request()
    def destroy(self) -> None:
        """Remove sub-surface interface

        The sub-surface interface is removed from the
        :class:`~pywayland.protocol.wayland.WlSurface` object that was turned
        into a sub-surface.
        """
        self._marshal(0)

    @WlSubsurface.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def set_position(self, x: int, y: int) -> None:
        """Reposition the sub-surface

        This schedules a sub-surface position change.

        :param x:
            x coordinate in the parent surface
        :type x:
            `ArgumentType.Int`
        :param y:
            y coordinate in the parent surface
        :type y:
            `ArgumentType.Int`
        """
        self._marshal(1, x, y)

    @WlSubsurface.request(
        Argument(ArgumentType.Object, interface=WlSurface),
    )
    def place_above(self, sibling: WlSurfaceProxy) -> None:
        """Restack the sub-surface

        This sub-surface is taken from the stack, and put back just above the
        reference surface.

        :param sibling:
            the reference surface
        :type sibling:
            :class:`~pywayland.protocol.wayland.WlSurface`
        """
        self._marshal(2, sibling)

    @WlSubsurface.request(
        Argument(ArgumentType.Object, interface=WlSurface),
    )
    def place_below(self, sibling: WlSurfaceProxy) -> None:
        """Restack the sub-surface

        The sub-surface is placed just below of the reference surface.

        :param sibling:
            the reference surface
        :type sibling:
            :class:`~pywayland.protocol.wayland.WlSurface`
        """
        self._marshal(3, sibling)

    @WlSubsurface.request()
    def set_sync(self) -> None:
        """Set sub-surface to synchronized mode

        Change the commit behaviour of the sub-surface to synchronized mode.
        """
        self._marshal(4)

    @WlSubsurface.request()
    def set_desync(self) -> None:
        """Set sub-surface to desynchronized mode

        Change the commit behaviour of the sub-surface to desynchronized mode.
        """
        self._marshal(5)


class WlSurfaceProxy(Proxy[WlSurface]):
    interface = WlSurface

    @WlSurface.request()
    def destroy(self) -> None:
        """Delete surface

        Deletes the surface and invalidates its object ID.
        """
        self._marshal(0)

    @WlSurface.request(
        Argument(ArgumentType.Object, interface=WlBuffer, nullable=True),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def attach(self, buffer: WlBufferProxy | None, x: int, y: int) -> None:
        """Set the surface contents

        Set a buffer as the content of this surface.

        :param buffer:
            buffer of surface contents
        :type buffer:
            :class:`~pywayland.protocol.wayland.WlBuffer` or `None`
        :param x:
            surface-local x coordinate
        :type x:
            `ArgumentType.Int`
        :param y:
            surface-local y coordinate
        :type y:
            `ArgumentType.Int`
        """
        self._marshal(1, buffer, x, y)

    @WlSurface.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def damage(self, x: int, y: int, width: int, height: int) -> None:
        """Mark part of the surface damaged

        This request is used to describe the regions where the pending buffer
        is different from the current surface contents.

        :param x:
            surface-local x coordinate
        :type x:
            `ArgumentType.Int`
        :param y:
            surface-local y coordinate
        :type y:
            `ArgumentType.Int`
        :param width:
            width of damage rectangle
        :type width:
            `ArgumentType.Int`
        :param height:
            height of damage rectangle
        :type height:
            `ArgumentType.Int`
        """
        self._marshal(2, x, y, width, height)

    @WlSurface.request(
        Argument(ArgumentType.NewId, interface=WlCallback),
    )
    def frame(self) -> WlCallbackProxy:
        """Request a frame throttling hint

        Request a notification when it is a good time to start drawing a new
        frame.

        :returns:
            :class:`~pywayland.protocol.wayland.WlCallback` -- callback object
            for the frame request
        """
        callback = self._marshal_constructor(3, WlCallback)
        return callback

    @WlSurface.request(
        Argument(ArgumentType.Object, interface=WlRegion, nullable=True),
    )
    def set_opaque_region(self, region: WlRegionProxy | None) -> None:
        """Set opaque region

        This request sets the region of the surface that is considered opaque.

        :param region:
            opaque region of the surface
        :type region:
            :class:`~pywayland.protocol.wayland.WlRegion` or `None`
        """
        self._marshal(4, region)

    @WlSurface.request(
        Argument(ArgumentType.Object, interface=WlRegion, nullable=True),
    )
    def set_input_region(self, region: WlRegionProxy | None) -> None:
        """Set input region

        This request sets the region of the surface for which the server will
        process input events.

        :param region:
            input region of the surface
        :type region:
            :class:`~pywayland.protocol.wayland.WlRegion` or `None`
        """
        self._marshal(5, region)

    @WlSurface.request(
        Argument(ArgumentType.Int),
        version=2,
    )
    def set_buffer_transform(self, transform: int) -> None:
        """Sets the buffer transformation

        This request sets an optional transformation on how the compositor
        interprets the contents of the buffer attached to the surface.

        :param transform:
            transform for interpreting buffer contents
        :type transform:
            `ArgumentType.Int`
        """
        self._marshal(6, transform)

    @WlSurface.request(
        Argument(ArgumentType.Int),
        version=3,
    )
    def set_buffer_scale(self, scale: int) -> None:
        """Sets the buffer scaling factor

        This request sets an optional scaling factor on how the compositor
        interprets the contents of the buffer attached to the window.

        :param scale:
            positive scale for the buffer
        :type scale:
            `ArgumentType.Int`
        """
        self._marshal(7, scale)

    @WlSurface.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        version=4,
    )
    def damage_buffer(self, x: int, y: int, width: int, height: int) -> None:
        """Mark part of the surface damaged using buffer coordinates

        This request is used to describe the regions where the pending buffer
        is different from the current surface contents, and where the damage is
        in buffer coordinates.

        :param x:
            buffer-local x coordinate
        :type x:
            `ArgumentType.Int`
        :param y:
            buffer-local y coordinate
        :type y:
            `ArgumentType.Int`
        :param width:
            width of damage rectangle
        :type width:
            `ArgumentType.Int`
        :param height:
            height of damage rectangle
        :type height:
            `ArgumentType.Int`
        """
        self._marshal(8, x, y, width, height)

    @WlSurface.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        version=5,
    )
    def offset(self, x: int, y: int) -> None:
        """Set the surface content offset

        The offset request sets the offset of the surface contents relative to
        the surface origin.

        :param x:
            surface-local x coordinate
        :type x:
            `ArgumentType.Int`
        :param y:
            surface-local y coordinate
        :type y:
            `ArgumentType.Int`
        """
        self._marshal(9, x, y)


class WlTouchProxy(Proxy[WlTouch]):
    interface = WlTouch

    @WlTouch.request(version=3)
    def release(self) -> None:
        """Release the touch object
        """
        self._marshal(0)


class WlBufferGlobal(Global[WlBuffer]):
    interface = WlBuffer


class WlCallbackGlobal(Global[WlCallback]):
    interface = WlCallback


class WlCompositorGlobal(Global[WlCompositor]):
    interface = WlCompositor


class WlDataDeviceGlobal(Global[WlDataDevice]):
    interface = WlDataDevice


class WlDataDeviceManagerGlobal(Global[WlDataDeviceManager]):
    interface = WlDataDeviceManager


class WlDataOfferGlobal(Global[WlDataOffer]):
    interface = WlDataOffer


class WlDataSourceGlobal(Global[WlDataSource]):
    interface = WlDataSource


class WlDisplayGlobal(Global[WlDisplay]):
    interface = WlDisplay


class WlKeyboardGlobal(Global[WlKeyboard]):
    interface = WlKeyboard


class WlOutputGlobal(Global[WlOutput]):
    interface = WlOutput


class WlPointerGlobal(Global[WlPointer]):
    interface = WlPointer


class WlRegionGlobal(Global[WlRegion]):
    interface = WlRegion


class WlRegistryGlobal(Global[WlRegistry]):
    interface = WlRegistry


class WlSeatGlobal(Global[WlSeat]):
    interface = WlSeat


class WlShellGlobal(Global[WlShell]):
    interface = WlShell


class WlShellSurfaceGlobal(Global[WlShellSurface]):
    interface = WlShellSurface


class WlShmGlobal(Global[WlShm]):
    interface = WlShm


class WlShmPoolGlobal(Global[WlShmPool]):
    interface = WlShmPool


class WlSubcompositorGlobal(Global[WlSubcompositor]):
    interface = WlSubcompositor


class WlSubsurfaceGlobal(Global[WlSubsurface]):
    interface = WlSubsurface


class WlSurfaceGlobal(Global[WlSurface]):
    interface = WlSurface


class WlTouchGlobal(Global[WlTouch]):
    interface = WlTouch


WlBuffer._gen_c()
WlBuffer.proxy_class = WlBufferProxy
WlBuffer.resource_class = WlBufferResource
WlBuffer.global_class = WlBufferGlobal


WlCallback._gen_c()
WlCallback.proxy_class = WlCallbackProxy
WlCallback.resource_class = WlCallbackResource
WlCallback.global_class = WlCallbackGlobal


WlCompositor._gen_c()
WlCompositor.proxy_class = WlCompositorProxy
WlCompositor.resource_class = WlCompositorResource
WlCompositor.global_class = WlCompositorGlobal


WlDataDevice._gen_c()
WlDataDevice.proxy_class = WlDataDeviceProxy
WlDataDevice.resource_class = WlDataDeviceResource
WlDataDevice.global_class = WlDataDeviceGlobal


WlDataDeviceManager._gen_c()
WlDataDeviceManager.proxy_class = WlDataDeviceManagerProxy
WlDataDeviceManager.resource_class = WlDataDeviceManagerResource
WlDataDeviceManager.global_class = WlDataDeviceManagerGlobal


WlDataOffer._gen_c()
WlDataOffer.proxy_class = WlDataOfferProxy
WlDataOffer.resource_class = WlDataOfferResource
WlDataOffer.global_class = WlDataOfferGlobal


WlDataSource._gen_c()
WlDataSource.proxy_class = WlDataSourceProxy
WlDataSource.resource_class = WlDataSourceResource
WlDataSource.global_class = WlDataSourceGlobal


WlDisplay._gen_c()
WlDisplay.proxy_class = WlDisplayProxy
WlDisplay.resource_class = WlDisplayResource
WlDisplay.global_class = WlDisplayGlobal


WlKeyboard._gen_c()
WlKeyboard.proxy_class = WlKeyboardProxy
WlKeyboard.resource_class = WlKeyboardResource
WlKeyboard.global_class = WlKeyboardGlobal


WlOutput._gen_c()
WlOutput.proxy_class = WlOutputProxy
WlOutput.resource_class = WlOutputResource
WlOutput.global_class = WlOutputGlobal


WlPointer._gen_c()
WlPointer.proxy_class = WlPointerProxy
WlPointer.resource_class = WlPointerResource
WlPointer.global_class = WlPointerGlobal


WlRegion._gen_c()
WlRegion.proxy_class = WlRegionProxy
WlRegion.resource_class = WlRegionResource
WlRegion.global_class = WlRegionGlobal


WlRegistry._gen_c()
WlRegistry.proxy_class = WlRegistryProxy
WlRegistry.resource_class = WlRegistryResource
WlRegistry.global_class = WlRegistryGlobal


WlSeat._gen_c()
WlSeat.proxy_class = WlSeatProxy
WlSeat.resource_class = WlSeatResource
WlSeat.global_class = WlSeatGlobal


WlShell._gen_c()
WlShell.proxy_class = WlShellProxy
WlShell.resource_class = WlShellResource
WlShell.global_class = WlShellGlobal


WlShellSurface._gen_c()
WlShellSurface.proxy_class = WlShellSurfaceProxy
WlShellSurface.resource_class = WlShellSurfaceResource
WlShellSurface.global_class = WlShellSurfaceGlobal


WlShm._gen_c()
WlShm.proxy_class = WlShmProxy
WlShm.resource_class = WlShmResource
WlShm.global_class = WlShmGlobal


WlShmPool._gen_c()
WlShmPool.proxy_class = WlShmPoolProxy
WlShmPool.resource_class = WlShmPoolResource
WlShmPool.global_class = WlShmPoolGlobal


WlSubcompositor._gen_c()
WlSubcompositor.proxy_class = WlSubcompositorProxy
WlSubcompositor.resource_class = WlSubcompositorResource
WlSubcompositor.global_class = WlSubcompositorGlobal


WlSubsurface._gen_c()
WlSubsurface.proxy_class = WlSubsurfaceProxy
WlSubsurface.resource_class = WlSubsurfaceResource
WlSubsurface.global_class = WlSubsurfaceGlobal


WlSurface._gen_c()
WlSurface.proxy_class = WlSurfaceProxy
WlSurface.resource_class = WlSurfaceResource
WlSurface.global_class = WlSurfaceGlobal


WlTouch._gen_c()
WlTouch.proxy_class = WlTouchProxy
WlTouch.resource_class = WlTouchResource
WlTouch.global_class = WlTouchGlobal
