# This file has been autogenerated by the pywayland scanner

# VENDORED FILE -- do not edit by hand.
#
# Generated by pywayland 0.4.19 scanner from the protocol XMLs vendored in
# this repo at launcher/data/. Upstream pywayland ships no
# wlr_foreign_toplevel_management_unstable_v1 module, so the generated output
# is committed here to make the switcher backend work out of the box.
#
# Regenerate with (from the repo root, .venv active):
#
#   sed 's/ interface="wl_object"//g' launcher/data/wayland.xml > /tmp/wayland.xml
#   python -m pywayland.scanner -o launcher/src/wayland_proto \
#       -i /tmp/wayland.xml launcher/data/wlr-foreign-toplevel-management-unstable-v1.xml
#
# The sed step drops the stale `interface="wl_object"` attribute carried by
# the vendored (older-revision) wayland.xml; pywayland's scanner requires
# every referenced interface to be declared in one of its input files, and
# wl_object is not a declared interface. Upstream's own generated module
# types that argument as plain `object` too.

# Copyright © 2018 Ilia Bozhinov
#
# Permission to use, copy, modify, distribute, and sell this
# software and its documentation for any purpose is hereby granted
# without fee, provided that the above copyright notice appear in
# all copies and that both that copyright notice and this permission
# notice appear in supporting documentation, and that the name of
# the copyright holders not be used in advertising or publicity
# pertaining to distribution of the software without specific,
# written prior permission.  The copyright holders make no
# representations about the suitability of this software for any
# purpose.  It is provided "as is" without express or implied
# warranty.
#
# THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
# SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
# SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
# AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
# ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
# THIS SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import Argument, ArgumentType, Global, Interface, Proxy, Resource

from .wayland import WlOutput
from .wayland import WlSeat
from .wayland import WlSeatProxy


class ZwlrForeignToplevelHandleV1(Interface):
    """An opened toplevel

    A :class:`ZwlrForeignToplevelHandleV1` object represents an opened toplevel
    window. Each app may have multiple opened toplevels.

    Each toplevel has a list of outputs it is visible on, conveyed to the
    client with the output_enter and output_leave events.
    """

    name = "zwlr_foreign_toplevel_handle_v1"
    version = 3

    class state(enum.IntEnum):
        maximized = 0
        minimized = 1
        activated = 2
        fullscreen = 3


class ZwlrForeignToplevelManagerV1(Interface):
    """List and control opened apps

    The purpose of this protocol is to enable the creation of taskbars and
    docks by providing them with a list of opened applications and letting them
    request certain actions on them, like maximizing, etc.

    After a client binds the :class:`ZwlrForeignToplevelManagerV1`, each opened
    toplevel window will be sent via the toplevel event
    """

    name = "zwlr_foreign_toplevel_manager_v1"
    version = 3


class ZwlrForeignToplevelHandleV1Resource(Resource[ZwlrForeignToplevelHandleV1]):
    interface = ZwlrForeignToplevelHandleV1

    @ZwlrForeignToplevelHandleV1.event(
        Argument(ArgumentType.String),
    )
    def title(self, title: str) -> None:
        """Title change

        This event is emitted whenever the title of the toplevel changes.

        :param title:
        :type title:
            `ArgumentType.String`
        """
        self._post_event(0, title)

    @ZwlrForeignToplevelHandleV1.event(
        Argument(ArgumentType.String),
    )
    def app_id(self, app_id: str) -> None:
        """App-id change

        This event is emitted whenever the app-id of the toplevel changes.

        :param app_id:
        :type app_id:
            `ArgumentType.String`
        """
        self._post_event(1, app_id)

    @ZwlrForeignToplevelHandleV1.event(
        Argument(ArgumentType.Object, interface=WlOutput),
    )
    def output_enter(self, output: WlOutput) -> None:
        """Toplevel entered an output

        This event is emitted whenever the toplevel becomes visible on the
        given output. A toplevel may be visible on multiple outputs.

        :param output:
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput`
        """
        self._post_event(2, output)

    @ZwlrForeignToplevelHandleV1.event(
        Argument(ArgumentType.Object, interface=WlOutput),
    )
    def output_leave(self, output: WlOutput) -> None:
        """Toplevel left an output

        This event is emitted whenever the toplevel stops being visible on the
        given output. It is guaranteed that an entered-output event with the
        same output has been emitted before this event.

        :param output:
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput`
        """
        self._post_event(3, output)

    @ZwlrForeignToplevelHandleV1.event(
        Argument(ArgumentType.Array),
    )
    def state(self, state: list) -> None:
        """The toplevel state changed

        This event is emitted immediately after the
        zlw_foreign_toplevel_handle_v1 is created and each time the toplevel
        state changes, either because of a compositor action or because of a
        request in this protocol.

        :param state:
        :type state:
            `ArgumentType.Array`
        """
        self._post_event(4, state)

    @ZwlrForeignToplevelHandleV1.event()
    def done(self) -> None:
        """All information about the toplevel has been sent

        This event is sent after all changes in the toplevel state have been
        sent.

        This allows changes to the :class:`ZwlrForeignToplevelHandleV1` to be
        sent as a group.
        """
        self._post_event(5)

    @ZwlrForeignToplevelHandleV1.event()
    def closed(self) -> None:
        """This toplevel has been destroyed

        This event means the toplevel has been destroyed. It is guaranteed that
        no more events will be sent for this toplevel.
        """
        self._post_event(6)


class ZwlrForeignToplevelManagerV1Resource(Resource[ZwlrForeignToplevelManagerV1]):
    interface = ZwlrForeignToplevelManagerV1

    @ZwlrForeignToplevelManagerV1.event(
        Argument(ArgumentType.NewId, interface=ZwlrForeignToplevelHandleV1),
    )
    def toplevel(self, toplevel: ZwlrForeignToplevelHandleV1) -> None:
        """A toplevel has been created

        This event is emitted whenever a new toplevel window is created. It is
        emitted for all toplevels, regardless of the app that has created them.

        All initial details of the toplevel(title, app_id, states, etc.) will
        be sent immediately after this event via the corresponding events in
        :class:`~pywayland.protocol.wlr_foreign_toplevel_management_unstable_v1.ZwlrForeignToplevelHandleV1`.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.wlr_foreign_toplevel_management_unstable_v1.ZwlrForeignToplevelHandleV1`
        """
        self._post_event(0, toplevel)

    @ZwlrForeignToplevelManagerV1.event()
    def finished(self) -> None:
        """The compositor has finished with the toplevel manager

        This event indicates that the compositor is done sending events to the
        :class:`ZwlrForeignToplevelManagerV1`. The server will destroy the
        object immediately after sending this request, so it will become
        invalid and the client should free any resources associated with it.
        """
        self._post_event(1)


class ZwlrForeignToplevelHandleV1Proxy(Proxy[ZwlrForeignToplevelHandleV1]):
    interface = ZwlrForeignToplevelHandleV1

    @ZwlrForeignToplevelHandleV1.request()
    def set_maximized(self) -> None:
        """Requests that the toplevel be maximized

        Requests that the toplevel be maximized. If the maximized state
        actually changes, this will be indicated by the state event.
        """
        self._marshal(0)

    @ZwlrForeignToplevelHandleV1.request()
    def unset_maximized(self) -> None:
        """Requests that the toplevel be unmaximized

        Requests that the toplevel be unmaximized. If the maximized state
        actually changes, this will be indicated by the state event.
        """
        self._marshal(1)

    @ZwlrForeignToplevelHandleV1.request()
    def set_minimized(self) -> None:
        """Requests that the toplevel be minimized

        Requests that the toplevel be minimized. If the minimized state
        actually changes, this will be indicated by the state event.
        """
        self._marshal(2)

    @ZwlrForeignToplevelHandleV1.request()
    def unset_minimized(self) -> None:
        """Requests that the toplevel be unminimized

        Requests that the toplevel be unminimized. If the minimized state
        actually changes, this will be indicated by the state event.
        """
        self._marshal(3)

    @ZwlrForeignToplevelHandleV1.request(
        Argument(ArgumentType.Object, interface=WlSeat),
    )
    def activate(self, seat: WlSeatProxy) -> None:
        """Activate the toplevel

        Request that this toplevel be activated on the given seat. There is no
        guarantee the toplevel will be actually activated.

        :param seat:
        :type seat:
            :class:`~pywayland.protocol.wayland.WlSeat`
        """
        self._marshal(4, seat)

    @ZwlrForeignToplevelHandleV1.request()
    def close(self) -> None:
        """Request that the toplevel be closed

        Send a request to the toplevel to close itself. The compositor would
        typically use a mechanism like XDG_RESPONSE to close the toplevel.
        """
        self._marshal(5)


class ZwlrForeignToplevelManagerV1Proxy(Proxy[ZwlrForeignToplevelManagerV1]):
    interface = ZwlrForeignToplevelManagerV1

    @ZwlrForeignToplevelManagerV1.request()
    def stop(self) -> None:
        """Stop sending events

        Indicates the client no longer wishes to receive events for new
        toplevels. However the compositor may emit further toplevel_created
        events, until the finished event is emitted.

        The client must not send any more requests after this one.
        """
        self._marshal(0)


class ZwlrForeignToplevelHandleV1Global(Global[ZwlrForeignToplevelHandleV1]):
    interface = ZwlrForeignToplevelHandleV1


class ZwlrForeignToplevelManagerV1Global(Global[ZwlrForeignToplevelManagerV1]):
    interface = ZwlrForeignToplevelManagerV1


ZwlrForeignToplevelHandleV1._gen_c()
ZwlrForeignToplevelHandleV1.proxy_class = ZwlrForeignToplevelHandleV1Proxy
ZwlrForeignToplevelHandleV1.resource_class = ZwlrForeignToplevelHandleV1Resource
ZwlrForeignToplevelHandleV1.global_class = ZwlrForeignToplevelHandleV1Global


ZwlrForeignToplevelManagerV1._gen_c()
ZwlrForeignToplevelManagerV1.proxy_class = ZwlrForeignToplevelManagerV1Proxy
ZwlrForeignToplevelManagerV1.resource_class = ZwlrForeignToplevelManagerV1Resource
ZwlrForeignToplevelManagerV1.global_class = ZwlrForeignToplevelManagerV1Global
